title:        CSV Converter
url:          http://kinlane.github.io/csv-converter/
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 100
paginate_path: "/blog/page:num"

production_url : http://kinlane.github.io/csv-converter/

BASE_PATH : http://kinlane.github.io/csv-converter/

categories_path : /categories.html
tags_path : /tags.html

org: kinlane
repo: csv-converter
resource: csv-converter
oauthio: qUDL4eZqKPFb41SwuWIYIwLR6jI

# Masthead title
masthead_link: http://kinlane.github.io/csv-converter/
masthead_font_size: 75
masthead_title: '{"CSV Converter"}'

# Feature
feature_title: API Design Providers Guide
feature_link: http://apis.how/xzca4kr2wb
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/3scale/report-image-api-design.png
feature_image_width: 45
